export const products = [
    {
        id: "1",
        name: "The Classic Chip",
        description: "Our signature cookie loaded with semi-sweet chocolate chunks and a hint of sea salt.",
        price: 4.50,
        image: "/images/classic-chip.jpg", // Placeholder
        category: "Classic",
        isBestseller: true,
        allergens: ["Gluten", "Dairy", "Eggs"],
    },
    {
        id: "2",
        name: "Midnight Double Chocolate",
        description: "Rich dark chocolate dough with white chocolate chips and cocoa nibs.",
        price: 4.75,
        image: "/images/double-chocolate.jpg",
        category: "Rich",
        isBestseller: true,
        allergens: ["Gluten", "Dairy", "Eggs", "Soy"],
    },
    {
        id: "3",
        name: "Oatmeal Raisin Walnut",
        description: "Chewy oatmeal cookie with plump raisins and toasted walnuts.",
        price: 4.50,
        image: "/images/oatmeal-raisin.jpg",
        category: "Classic",
        isBestseller: false,
        allergens: ["Gluten", "Dairy", "Eggs", "Nuts"],
    },
    {
        id: "4",
        name: "Birthday Cake",
        description: "Vanilla sugar cookie with rainbow sprinkles and a white chocolate drizzle.",
        price: 4.75,
        image: "/images/birthday-cake.jpg",
        category: "Fun",
        isBestseller: true,
        allergens: ["Gluten", "Dairy", "Eggs"],
    },
    {
        id: "5",
        name: "Salted Caramel Pretzel",
        description: "Sweet and salty perfection with caramel bits and crushed pretzels.",
        price: 5.00,
        image: "/images/salted-caramel.jpg",
        category: "Savory",
        isBestseller: false,
        allergens: ["Gluten", "Dairy", "Eggs"],
    },
    {
        id: "6",
        name: "Vegan Choco Chunk",
        description: "All the flavor of our classic chip, but 100% plant-based.",
        price: 5.00,
        image: "/images/vegan-choco.jpg",
        category: "Vegan",
        isBestseller: false,
        allergens: ["Gluten", "Soy", "Nuts"],
    },
]

export const reviews = [
    {
        id: "1",
        user: "Sarah J.",
        rating: 5,
        comment: "The best cookies I've ever had! The sea salt on the chocolate chip is a game changer.",
        date: "2023-10-15",
    },
    {
        id: "2",
        user: "Mike T.",
        rating: 5,
        comment: "Ordered a box for my office and they were gone in minutes. Highly recommend!",
        date: "2023-11-02",
    },
    {
        id: "3",
        user: "Emily R.",
        rating: 4,
        comment: "Delicious, but I wish they had more gluten-free options.",
        date: "2023-11-20",
    },
]
